### ISSUE TITLE
Cannot create DAO proposal

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-frontend#104]
Creating a proposal does work, but the frontend shows an error nevertheless.
![Screenshot 2023-05-23 at 18 14 52](https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/99559869/bf779f15-48e4-4c47-adcf-ba2c83523922)
![Screenshot 2023-05-23 at 18 15 02](https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/99559869/869d112d-f356-421f-a956-cef8b206dd8e)

**Comment by GHesericsu** [comment]
Not able to produce errors anymore. Most likely it's an error fetching from DB
