### ISSUE TITLE
User not recognized as admin

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-frontend#118]
- Create a DAO
- Enter email, logo, descriptions
- On the “Governance” reload the page
- Connect wallet again
- Error “Sorry, you are not the admin of Deep Ink Vent. I”
- Even going back to DAO detail page, then clicking “Customize DAO” results in the error
- See img “not-admin.png” with console (owner_id matches my wallet)
- It only works if I go back to the homepage then open the DAO detail again and click “Customize DAO”

![not-admin](https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/99559869/cf14dab6-7d56-40aa-a243-1f897fd2bfde)

**Comment by deep-ink-ventures** [comment]
Low prio

**Comment by GHesericsu** [comment]
fixed.
