### ISSUE TITLE
Distribute more tokens than available

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-frontend#121]
If I, by accident, try to distribute more tokens that are available (e.g. there are 1M tokens available and I enter 600k in the input of 2 people), then there is a JS error and no error message displayed to the user. JS error “Uncaught (in promise) Error: createType(Call):: Call: failed decoding assets.transfer:: Struct: failed on args: {"id":"u32","target":"MultiAddress","amount":"Lookup110"}:: Struct: failed on amount: Compact<u128>:: u128: Negative number passed to unsigned type”

**Comment by GHesericsu** [comment]
fixed. It will give warnings now
