### ISSUE TITLE
Proposal created although tx was cancelled

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-frontend#127]
I cancelled creating a proposal on the first, second and third wallet prompt. All proposals were still created. Though the first one without any fields. See img “cancel-proposal” 

![cancel-proposal](https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/99559869/dfbc4eba-c649-4b0b-8851-3c100e3341ca)

**Comment by GHesericsu** [comment]
Fixed. Filtered out all the incomplete proposals.
