### ISSUE TITLE
Proposal duration not displayed correctly

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-frontend#132]
I created a new DAO, set 1 day as the proposal duration. Created a proposal and the proposal duration was 4 minutes. See img “proposal-duration”
![proposal-duration](https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/99559869/4a30cda9-3af5-4900-9192-1d557557fa2f)

**Comment by deep-ink-ventures** [comment]
That’s on purpose to make testing faster, just make sure the copy is correct
