### ISSUE TITLE
Not possible to distribute 100% of all tokens

### ISSUE THREAD

**Issue by jazzbah** [deep-ink-ventures/genesis-dao-frontend#138]
1. Created a DAO with 100.000 tokens
2. Distribute 80k to one wallet
3. Distribute 20k to the other wallet
4. Try to submit the form by clicking the CTA
5. => no effect, no error and no message to the user
6. => It only worked after reducing one value (I did 20.000 -> 19.999)

When clicking the submit button the first input was focused so this looks like a FE issue.

**Comment by GHesericsu** [comment]
fixed
