### ISSUE TITLE
Build dashboard

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-frontend#149]
Build the dashboard as per the design. The [stats endpoint](https://service.genesis-dao.org/redoc/#operation/Retrieve%20stats) can be used to retrieve the basic stats.

**Comment by hornilla-jowelyn** [comment]
to do: integrate widget data when backend is available @x-xo

**Comment by x-xo** [comment]
Waiting for https://github.com/deep-ink-ventures/genesis-dao-service/issues/20
