### ISSUE TITLE
Allow users to select the account they want to connect with

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-frontend#153]
It seems that upon connecting to an account, the frontend currently picks the first, visible, account available without letting a user choose another option.

This should be changed to allow for manual selection of the account that should be used.

**Comment by deep-ink-ventures** [comment]
A sample solution can be found at acala:

<img width="707" alt="Screenshot 2023-07-06 at 12 32 02" src="https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/120174523/a27f17d4-1e63-4487-ad35-785574772ea3">

**Comment by GHesericsu** [comment]
Done
