### ISSUE TITLE
Don't empty DAO creation input fields when submitting a TX

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-frontend#198]
When a user creates a new DAO they have to provide the DAO name and ID. They then have to confirm the transaction - when they do so, the frontend clears the input fields for the DAOs.

This should be changed so the input remains. In case there is an error, users then don't have to enter all the details again.

<img width="1172" alt="CleanShot 2023-08-16 at 12 05 04@2x" src="https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/99559869/4ebdcbc4-43fa-4e94-9200-4617b832ceab">

**Comment by hornilla-jowelyn** [comment]
https://github.com/deep-ink-ventures/genesis-dao-frontend/pull/196
