### ISSUE TITLE
Send governance transactions to multisig wallet

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-frontend#207]
All governance actions for a DAO (send tokens out of the treasury, destroy DAO, change owner, ...) should be submitted to the multisig wallet of the DAO since these actions have to be signed by all council members.

These actions later should show up under the DAO's "Transactions" section so council members can review and approve these actions.

**Comment by GHesericsu** [comment]
transfer assets and change owner are done.
