### ISSUE TITLE
Fix isAdmin variable in AssetsTable

### ISSUE THREAD

**Issue by GHesericsu** [deep-ink-ventures/genesis-dao-frontend#236]
https://github.com/deep-ink-ventures/genesis-dao-frontend/blob/d3299955c509d8b5942b62885d70bbacda0e55b7/src/components/AssetsTable.tsx#L39

should check if the user's publickey is in the adminAddresses array or the daoOwner. Creator is not necessary an admin.

**Comment by hornilla-jowelyn** [comment]
https://github.com/deep-ink-ventures/genesis-dao-frontend/pull/245

https://github.com/deep-ink-ventures/genesis-dao-frontend/pull/242
