### ISSUE TITLE
Refactor postMultiSigTxn to prevent user txn abandonment 

### ISSUE THREAD

**Issue by GHesericsu** [deep-ink-ventures/genesis-dao-frontend#249]
Make users sign challenge string first- > send multisig transaction onchain -> post multisig transaction offchain

**Comment by hornilla-jowelyn** [comment]
https://github.com/deep-ink-ventures/genesis-dao-frontend/pull/277

**Comment by hornilla-jowelyn** [comment]
https://github.com/deep-ink-ventures/genesis-dao-frontend/pull/278 needs testing
