### ISSUE TITLE
Padding missing

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/genesis-dao-frontend#99]
Council & distribute tokens page: Form needs padding left & right.

![add-padding-tokens-page](https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/99559869/a17bdc4c-21f0-4802-bcb4-ba8810647698)

**Comment by GHesericsu** [comment]
hmm I tried to reproduce but I couldn't.

**Comment by GHesericsu** [comment]
@x-xo

**Comment by GHesericsu** [comment]
The image is without the extra paddings:
![Screen Shot 2023-05-17 at 12 59 55 AM](https://github.com/deep-ink-ventures/genesis-dao-frontend/assets/60202455/6362b9f4-a382-48b7-9c65-14b5d4ac1da8)


But I added extra padding on two sides.
